### ISSUE TITLE
Error when opening OpenAPI documentation page in English

### ISSUE THREAD

**Issue by ruven** [MOM-CNRS/Opentheso#103]
When you go to the OpenAPI documentation page from a link on the index page of a particular thesaurus (for example https://opentheso.huma-num.fr/opentheso/openapi/doc/) you get the API definitions in French and it everything works fine.

However, if you try to switch to English using the menu at the top, you get an error with the latest version of Opentheso: https://opentheso.huma-num.fr/opentheso/openapi/doc/?lang=en&version=v1 I think this used to work correctly before. Is it a config error or maybe a missing template?

**Comment by miledrousset** [comment]
thanks Ruven for the warning, I've corrected it

**Comment by ruven** [comment]
Thanks, but how did you fix it? This is also broken on my own OpenTheso installations.

**Comment by miledrousset** [comment]
Tu travailles en Tomcat 9 ou Tomcat 10 ?

**Comment by miledrousset** [comment]
Il manquait ces 3 lignes dans le fichier de langues (openapi_en.properties)
getListLang.summary=Récupère la liste des langues d'un thesaurus
getListLang.description=Ancienne version : `/api/info/listLang?theso=<idTheso>`\n\nPermet de connaitre la liste des langues d'un thesaurus
getListLang.200.description=Renvoie la liste des langues d'un thésaurus au format Json
getListLang.thesaurusId.description=Identifiant du thesaurus.

**Comment by ruven** [comment]
J'utilise docker, qui est basé sur Tomcat 9.

OK merci. Il faudra re-générer le fichier .war avec la correction j'imagine. Dans ce cas, j'attendrai la prochaine version - n'oublies pas d'inclure cette correction dedans!
