### ISSUE TITLE
Url api d'un concept

### ISSUE THREAD

**Issue by Daniel-KM** [MOM-CNRS/Opentheso#18]
Bonjour,

Dans l'[aide](https://github.com/miledrousset/Opentheso2/raw/master/src/main/resources/install/webservices.pdf) sur les services, il est indiqué que les concepts ont des adresses pour l'api, par exemple "https://pactols.frantiq.fr/opentheso/api/26678/pcrtkOgxvd4Ijy.jsonld". Quelles sont celles qui correspondent au concept https://opentheso.huma-num.fr/opentheso/?idc=doi:10.34817/sv-a3ah58wd&idt=th184 qui a l'identifiant doi:10.34817/sv-a3ah58wd ?
En fait, cela va permettre de créer un [suggéreur générique](https://gitlab.com/Daniel-KM/Omeka-S-module-ValueSuggestAny) pour Omeka.

**Comment by miledrousset** [comment]
Bonjour, dans votre cas, vous avez du importer un thésaurus avec des identifiants DOI, ils ont été traité comme des identifiants classique (id), je n'ai pas implémenter encore la reconnaissance des DOI.
Il faudrait qu'on en discute, envoyez moi un mail en privé pour faire des tests 
Cordialement

**Comment by miledrousset** [comment]
J'ajoute que la même URL devrait être comme ceci : 
https://opentheso.huma-num.fr/opentheso/api/th184.doi:10.34817/sv-a3ah58wd.json
mais la présence d'un (/) dans l'identifiant ( doi:10.34817**/**sv-a3ah58wd) empêche le bon focntionnement du webservices et ne permet pas de détecter la bonne action.

**Comment by Daniel-KM** [comment]
Ce n'est pas un thésaurus que je gère, j'essaie de faire un module générique. 

A priori, les doi fonctionne comme les handle. et dans les ark aussi il y a une "/". Une autre solution est d'ajouter le numéro d'id interne en identifiant dans le skos, voire même l'url complète "https://opentheso.huma-num.fr/opentheso/api/th184.doi:10.34817/sv-a3ah58wd", comme cela il n'y aura pas de doute possible.

**Comment by Daniel-KM** [comment]
Ce n'est pas un thésaurus que je gère, j'essaie de faire un module générique. 

A priori, les doi fonctionnent comme les handle. et dans les ark aussi il y a une "/". Une autre solution est d'ajouter le numéro d'id interne en identifiant dans le skos, voire même l'url complète "https://opentheso.huma-num.fr/opentheso/api/th184.doi:10.34817/sv-a3ah58wd", comme cela il n'y aura pas de doute possible.

**Comment by miledrousset** [comment]
Cette solution est complexe à mettre en place, ca suppose un changement majeur dans le fonctionnement, voici comment ca fonctionne la récupération : 
- récupération par IdConcept = il faut impérativement l'identifiant du thésaurus, parce qu'on important un thésaurus 2 fois, on peut avoir 2 fois le même identifiant dans une seule instance.
- récupération par idArk = il faut dans ce cas que la table du concept contient l'identifiant ark, donc il n'y a pas de doute que c'est unique, donc par d'obligation de fournir l'id du thésaurus, donc ca peut marcher
- récupération par IdHandle = idem que pour ark
- récupération par DOI (c'est votre cas) = comme le thésaurus à l'import, il n'y a pas eu de détection des identifiants DOI pour les intégrer dans le champ DOI du concept, alors on se retrouve avec un identifiant simple pour le concept, donc il faut impérativement l'id du thésaurus pour trouver le bon concept
mais comme il y a un (/) dans l'identifiant, alors le webservice ne trouve pas la bonne requête pour (th184.doi:10.34817/sv-a3ah58wd.json) donc problème !
Solution : 
1. il faut que j'ajoute l'option d'import de thésaurus avec DOI (c'est la plus viable et pérenne)
2. trouver une solution avec le webservices pour contourner le (/)

**Comment by Daniel-KM** [comment]
Pour les exceptions, je gère cela dans un code spécifique pour l'instant.

**Comment by miledrousset** [comment]
J'ai intégré l'option d'import des thésaurus avec des identifiants DOI, mais il reste à gérer la génération d'identifiants DOI pour les nouveaux concepts, c'est en cours.

**Comment by Daniel-KM** [comment]
Ok merci. J'attends de voir si opentheso l'a mis en production. Avec quoi créez-vous les doi ?

**Comment by miledrousset** [comment]
Justement, j'ai bien précisé que la création d'identifiants DOI en cours de négociation, comme c'est payant, il faut trouver une solution viable, c'est en cours ....
