### ISSUE TITLE
Importing skos:editorialNote causes strange results

### ISSUE THREAD

**Issue by adamretter** [MOM-CNRS/Opentheso#22]
Importing the following SKOS in RDF Turtle format:

```ttl
@prefix dct:     <http://purl.org/dc/terms/> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix tna:     <http://www.nationalarchives.gov.uk/> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .

<http://www.nationalarchives.gov.uk/ont.taxonomy.tna> rdf:type skos:ConceptScheme;
  dct:title "TNA Taxonomy" ;
  dct:language "en" ;
  dct:creator "Evolved Binary" ;
  dct:created "2021-02-18T17:10:00+01:00"^^xsd:dateTime .

<http://www.nationalarchives.gov.uk/topic.31>
      a       skos:Concept ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Forestry" .

<http://www.nationalarchives.gov.uk/topic.43>
      a       skos:Concept ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Merchant seaman" ;
      skos:related <http://www.nationalarchives.gov.uk/topic.55> ;
      skos:editorialNote "Example: I have decided to associate this with Public Disorder, as there are many records about Merchant seamen involved in acts of Public Disorder" .

<http://www.nationalarchives.gov.uk/topic.3R>
      a       skos:Concept ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Litigation" .

<http://www.nationalarchives.gov.uk/topic.55>
      a       skos:Concept ;    
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Public disorder" ;
      skos:broader <http://www.nationalarchives.gov.uk/topic.3R> .
```

Gives a strange view like the following, I had rather expected the preferred labels to appear in the Tree and not the Local Identifiers.

![opentheso2-strange1](https://user-images.githubusercontent.com/1264057/108407423-039de280-7224-11eb-814f-3c9901e51b9c.png)

In addition, the tabs `Index`, `Collection`, and `Tree` remain empty too!

**Comment by miledrousset** [comment]
Your thesaurus was imported with the source language French, but the thesaurus is in English:
change the thesaurus to the default source language (English),
force the language of the notes with (@en)
skos: editorialNote "Example: I have decided to associate this with Public Disorder, as there are many records about Merchant seamen involved in acts of Public Disorder @ en.

**Comment by adamretter** [comment]
> Your thesaurus was imported with the source language French, but the thesaurus is in English:
change the thesaurus to the default source language (English)

I could not find a mechanism to do that. It allowed me to create an additional language of English, but I couldn't seem to get it to change the default language.

We did set `workLanguage=en` during installation.

> force the language of the notes with (@en)

Thanks. I will try converting our `skos:prefLabel` from `xsd:string` to `rdf:langString` and see if that helps...

**Comment by miledrousset** [comment]
I confirm, it's a bug, it's fixed. I will do an update next week. 
Thank you

**Comment by miledrousset** [comment]
I imported your example, it works 
![Capture d’écran 2021-02-19 à 14 35 11](https://user-images.githubusercontent.com/3404662/108511302-064e1580-72c0-11eb-9411-7d103d80c607.png)
![Capture d’écran 2021-02-19 à 14 35 26](https://user-images.githubusercontent.com/3404662/108511318-0a7a3300-72c0-11eb-9a3f-d1206d45c157.png)

**Comment by adamretter** [comment]
@miledrousset Okay great.
I am guessing that you created the concept 'amphore' as it's not in our taxonomy?

**Comment by miledrousset** [comment]
yes indeed ;)  I simply tested the automatic alignment to verify that the language is well processed
