### ISSUE TITLE
Importing SKOS with non-SKOS properties causes strange results

### ISSUE THREAD

**Issue by adamretter** [MOM-CNRS/Opentheso#23]
Importing the following SKOS in RDF Turtle format (which includes non-SKOS properties such as `schema:identifier`) :

```ttl
@prefix schema:  <http://schema.org/> .
@prefix dct:     <http://purl.org/dc/terms/> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix tna:     <http://www.nationalarchives.gov.uk/> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .

<http://www.nationalarchives.gov.uk/ont.taxonomy.tna> rdf:type skos:ConceptScheme;
  dct:title "TNA Taxonomy" ;
  dct:language "en" ;
  dct:creator "Evolved Binary" ;
  dct:created "2021-02-18T17:10:00+01:00"^^xsd:dateTime .

<http://www.nationalarchives.gov.uk/topic.31>
      a       skos:Concept ;
      schema:identifier
              [ schema:propertyId <http://www.nationalarchives.gov.uk/ont.mongo_id> ;
                schema:value "C10040"
              ] ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Forestry" .

<http://www.nationalarchives.gov.uk/topic.43>
      a       skos:Concept ;
      schema:identifier
              [ schema:propertyId <http://www.nationalarchives.gov.uk/ont.mongo_id> ;
                schema:value "C10063"
              ] ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Merchant seaman" ;
      skos:related <http://www.nationalarchives.gov.uk/topic.55> ;
      skos:editorialNote "I have decided to associate this with Public Disorder, as there are many records about Merchant seamen involved in acts of Public Disorder" .

<http://www.nationalarchives.gov.uk/topic.3R>
      a       skos:Concept ;
      schema:identifier
              [ schema:propertyId <http://www.nationalarchives.gov.uk/ont.mongo_id> ;
                schema:value "C10055"
              ] ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Litigation" .

<http://www.nationalarchives.gov.uk/topic.55>
      a       skos:Concept ;
      schema:identifier
              [ schema:propertyId <http://www.nationalarchives.gov.uk/ont.mongo_id> ;
                schema:value "C10086"
              ] ;
      skos:inScheme <http://www.nationalarchives.gov.uk/ont.taxonomy.tna> ;
      skos:prefLabel "Public disorder" ;
      skos:broader <http://www.nationalarchives.gov.uk/topic.3R> .
```

Gives a strange view like the following, it seems to mix up the labels used in the `Concept` tab.
![opentheso2-strange2](https://user-images.githubusercontent.com/1264057/108407947-bbcb8b00-7224-11eb-9024-2d6071ce9178.png)

Similarly to https://github.com/miledrousset/Opentheso2/issues/22, the tabs `Index`, `Collection`, and `Tree` remain empty too!

**Comment by miledrousset** [comment]
Do you have the possibility to replace (schema:identifier .....)
by
dcterms:identifier "31";
I note this problem on the task list 

Similarly to #22, the tabs Index, Collection, and Tree remain empty too! => I answered this problem

**Comment by adamretter** [comment]
> Do you have the possibility to replace (schema:identifier .....) by dcterms:identifier "31";

Not easily!

We use `dct:identifier` already as the primary identifier, we then also use one or more `schema:identifier` as secondary identifiers.

These secondary identifiers are for linking the entity to other systems, `schema:identifier` allows us to specify a Object Property so we can indicate the type of identifier along with its value.

> I note this problem on the task list

Thanks, do you track these via GitHub issues or another system?

**Comment by miledrousset** [comment]
do you want to keep this id or ignore?
if so, in which SKOS property it should be stored (Notation, notes, altLabel ....)

**Comment by miledrousset** [comment]
**Thanks, do you track these via GitHub issues or another system?**
We work with Trello for the management of bugs and actions

**Comment by adamretter** [comment]
> do you want to keep this id or ignore?
> if so, in which SKOS property it should be stored (Notation, notes, altLabel ....)

We want to keep it. Ideally it should be round-tripped as is, i.e. remain a dct:identifier
