### ISSUE TITLE
Export-import d'un thésaurus

### ISSUE THREAD

**Issue by ghost** [MOM-CNRS/Opentheso#28]
Bonjour,

J'ai réalisé une petite expérience avec Opentheso2 en utilisant la fonction export et import de thésaurus dans la boîte à outils. Mon besoin initial était le suivant : exporter mon thésaurus afin de modifier les URI de mes concepts avant de le réimporter pour voir si les changements avaient été gérés par le système. Je me suis premièrement inspiré du fichier "Exemple_import_CSV" disponible dans le Carnet Hypotheses d'Opentheso : j'ai ainsi renseigné la colonne "URI" du tableur avec la valeur d'ID interne que je souhaitais obtenir.
Sans être parvenu à obtenir la réponse à mon questionnement, j'ai alors remarqué deux grosses problématiques : 

- tout d'abord, les définitions que j'avais rentrées dans Opentheso à certains de mes concepts se sont retrouvées complètement tronquées et scindées entre plusieurs colonnes. Ainsi, le début de la phrase est dans la colonne appropriée, celle skos:definition@fr, mais la chaîne de caractère se poursuit dans les colonnes skos:definition@gr, la, etc.
![Capture d’écran de 2021-06-04 11-44-34](https://user-images.githubusercontent.com/71893470/120782743-9a1fb680-c52a-11eb-8aa5-1a7db9908329.png)
Est-ce un problème suscité par l'ouverture du fichier CSV dans un tableur ? (sachant que je me suis servi de LibreOffice Calc & de Google Sheets indépendamment). Comment y remédier ?

- Je n'ai ensuite pas pu réaliser la réimportation de mon fichier CSV modifié dans Opentheso, en raison de l'apparition d'un message d'erreur lors de l'upload : 
![Capture d’écran de 2021-06-04 11-25-20](https://user-images.githubusercontent.com/71893470/120782990-dd7a2500-c52a-11eb-8bd3-7f9c58555357.png)
Je n'ai pourtant modifié aucun header, et ne suis intervenu que dans les champs "modifiables" du thésaurus... L'upload du fichier "exemple", qui dispose des mêmes en-têtes, a par contre bien été réussi.
Voici l'impasse qui m'a un peu éloigné de ma préoccupation initiale, mais ces problèmes me semblaient assez importants pour être signalés.

Merci pour toute aide,
Rémy

**Comment by miledrousset** [comment]
Bonjour Rémy,
J'ai exporté ton thésaurus (j'ai réussi à le trouver grâce à tes captures d'écrans ;) 
Je l'ai exporté en CSV, puis je l'ai réimporté de suite, ca passe sans problème. 
Donc, le problème est forcément lié au traitement que tu as fait via le tableur.
Il y a forcément un souci lié à l'enregistrement du fichier (UTF-8, séparateur ....).
Pour mieux cerner le problème, envoir moi ton fichier modifié pour regarder.

**Comment by miledrousset** [comment]
à l'export en CSV, il faut choisir un autre séparateur que la virgule (,) puisqu'elle est utilisée souvent dans tes notes

**Comment by ghost** [comment]
Bonjour Miled,

Merci pour ces réponses : j'ai changé le séparateur à l'export par \t et paramétré le tableur pour n'y ajouter que des tabulations (ni virgules ni points-virgules), et heureusement l'import fonctionne très bien ! Le problème venait bien de moi et de mes manipulations.
Pour finir, j'ai obtenu la réponse à ma première question : il est difficile de changer les IDs internes à mon thésaurus car cela demanderait de modifier un par un tous les liens de relation que j'ai déjà insérés... ce qui est un peu fastidieux. La seule alternative est de recréer les concepts, ce que je ferai dans un nouveau thésaurus quand je serai déclaré apte à quitter mon « bac à sable » ;-)
Je te remercie encore pour ton aide,

Bien cordialement,
Rémy

**Comment by miledrousset** [comment]
Ecris moi à mon adresse directement, je te donnerai quelques pistes !
