### ISSUE TITLE
Problème de copie entre thésaurus ?

### ISSUE THREAD

**Issue by cmasset** [MOM-CNRS/Opentheso#51]
Bonjour,

Tout d'abord bravo pour ce projet !

Je crois qu'il y a un souci dans la copie d'une branche depuis un thésaurus vers un autre. En effet quand j'essaye de copier une branche d'un thésaurus 1 dans un thésaurus 2 (sous un top-term, par exemple, comme vous pouvez le voir dans le screenshot lié), la branche est bien copiée, mais elle s'affiche également au niveau supérieur, comme nouveau top-term du thésaurus 2 (cf "thesaurus1_term1" sur le screenshot). Et il s'agit bien de la même branche dans la base de données, simplement elle s'affiche à deux endroits dans le thésaurus 2.

Merci par avance (nous utilisons la release Opentheso-22.09) !

![testCopyOpentheso](https://user-images.githubusercontent.com/53078476/193035564-3f30916b-c9f8-423a-9ddc-1d587fb83fee.jpg)

**Comment by cmasset** [comment]
On constate effectivement dans l'export du "thésaurus 2" que le terme copié a aussi été ajouté en "top terme".
 
![testCopyOpentheso2](https://user-images.githubusercontent.com/53078476/193039908-31951a9f-62cf-4933-99dd-2054bc067235.jpg)

**Comment by miledrousset** [comment]
Bonjour,
Effectivement, j'ai pu reproduire le Bug, il se produit quand on copie une branche de la racine vers un autre thésaurus. 
Pour contourner le problème, il suffit de supprimer la relation BT générique, puis replacer la branche là où voulez.
J'ai constaté également qu'on ne peut pas coller à la racine, je vais mettre ce bug à la liste des taches.
Merci pour le signalement

**Comment by cmasset** [comment]
D'accord merci !

**Comment by miledrousset** [comment]
C'est corrigé avec la nouvelle version https://github.com/miledrousset/Opentheso2/releases/tag/v22.10

**Comment by cmasset** [comment]
Super merci !
