### ISSUE TITLE
Installation OpenTheso Windows

### ISSUE THREAD

**Issue by Juliettejns** [MOM-CNRS/Opentheso#53]
Bonjour,

Tout d'abord merci beaucoup pour le partage de votre projet! Nous nous intéressons à OpenTheso dans le cadre d'une refonte de notre site du [MeSH bilingue](https://mesh.inserm.fr/FrenchMesh/), un vocabulaire contrôlé pour l'indexation du biomédical, géré par l'Inserm.

Dans ce contexte, nous effectuons des premiers tests d'utilisation et souhaitions installer OpenTheso en local. Si nous réussissons à faire fonctionner notre propre instance sur Linux, ce n'est pas le cas sur Windows. OpenTheso s'affiche bien dans notre navigateur mais impossible de cliquer sur les éléments et nous obtenons le message d'erreur ci-joint:

![image](https://user-images.githubusercontent.com/56683417/195832504-bc47363e-0edb-4316-af36-01a3d0d848b9.png)

Il me semble que la connexion à la base de données n'est pas possible. Mais même en modifiant et vérifiant les paramètres de connexion dans le fichier hikari et dans PgAdmin, nous continuons d'avoir ce problème... Pourriez-vous nous aider sur ce souci?

En vous remerciant d'avance,

Juliette Janes pour l'équipe MeSH de l'Information Scientifique et Technique de l'Inserm

 

Environnement de travail: Windows 10, Java 11, PostGreSQL 14, TomCat9 et opentheso.war 22.10

Une deuxième tentative a été effectuée en utilisant TomCat10 mais le résultat reste le même. Nous nous sommes basés sur la documentation suivante pour l'installation: https://github.com/miledrousset/Opentheso2/blob/master/src/main/resources/install/Installer%20Opentheso%20sous%20Windows.pdf

**Comment by miledrousset** [comment]
Bonjour,
Merci tout d’abord pour votre confiance.

A première vue, c’est un problème de base de données, le Pool de connexion ne s’initialise pas.
Il y a aussi un problème d’accents, c’est bizarre …

Si vous avez un moment pour une visio, j’ai une petite heure devant moi maintenant,
Sinon, lundi, je peux vous débloquer ce qui pose problème.

Cordialement

**Comment by Juliettejns** [comment]
Merci beaucoup pour votre réactivité!

Nous ne sommes malheureusement pas disponible cette après-midi mais une visio lundi nous convient tout à fait. Quelles sont vos disponibilités? 

Cordialement,
Juliette Janès

**Comment by miledrousset** [comment]
Je suis dispo lundi à 11h00,
Sinon 15h00
(écrivez moi directement pour avoir votre mail et vous envoyer un lien de Visio)
Miled

Le 14 oct. 2022 à 15:13, Juliettejns ***@***.******@***.***>> a écrit :



Merci beaucoup pour votre réactivité!

Nous ne sommes malheureusement pas disponible cette après-midi mais une visio lundi nous convient tout à fait. Quelles sont vos disponibilités?

Cordialement,
Juliette Janès

**Comment by miledrousset** [comment]
Je viens de refaire la doc pour l'installation sous windows.
https://github.com/miledrousset/Opentheso2/blob/dev/src/main/resources/install/Installer%20Opentheso%20sous%20Windows.pdf
