### ISSUE TITLE
Problème Import thésaurus csv

### ISSUE THREAD

**Issue by Juliettejns** [MOM-CNRS/Opentheso#55]
Bonjour,
 
Dans le cadre de la refonte de notre service du MeSH bilingue, nous effectuons des tests d'utilisation d'OpenTheso. 

Actuellement, nous nous intéressons à la fonctionnalité d'import d'un thésaurus en csv dans notre instance locale. Si un thésaurus est effectivement bien créé lors de l'import, il nous manque à chaque fois des éléments.
En important des csv exemples fournis par Opentheso et par sa documentation, nous arrivons également au même problème. Les éléments altlabel, description, note et historynote ne sont pas générés.

Auriez-vous une idée de ce qui cause ce problème?

Vous trouverez ci-joint le csv importé et une capture d'écran du résultat obtenu dans notre instance OpenTheso.

En vous remerciant d'avance,
 
Juliette Janes pour l'équipe MeSH de l'Information Scientifique et Technique de l'Inserm

 
Environnement de travail: Windows 10, Java 11, PostGreSQL 14, TomCat9 et opentheso.war 22.10.1

Le csv importé: [20221109_MeSH_1_param.csv](https://github.com/miledrousset/Opentheso2/files/9972525/20221109_MeSH_1_param.csv)

Le résultat pour un concept dans OpenTheso:
 ![image](https://user-images.githubusercontent.com/56683417/200872534-ae4bb28e-9a10-45ba-b131-28c282671e22.png)
[](url)

**Comment by miledrousset** [comment]
Bonjour,
Effectivement, j'ai vu ce bug, je vais le corriger dans la semaine.
Merci pour le signalement.

**Comment by miledrousset** [comment]
J'ai corrigé le problème, je vais déposer dans quelques jours une nouvelle version sur GitHub.
Voici la copie d'écran du thésaurus importé sur ma machine !
<img width="1465" alt="Capture d’écran 2022-11-14 à 09 45 37" src="https://user-images.githubusercontent.com/3404662/201615784-39de9e81-d19e-40a4-8604-8be872604ba8.png">

**Comment by Juliettejns** [comment]
Bonjour, 
Je vous remercie pour votre réponse et cette information.
Merci pour cette copie d'écran:)
Une bonne semaine, 
Juliette Janès
