### ISSUE TITLE
Are bulk edits possible

### ISSUE THREAD

**Issue by jpadfield** [MOM-CNRS/Opentheso#84]
Hi, I am exploring how I can manage terms which I am organising in OpenTheso2 but are referenced from elsewhere I am also working with collections/groups.

The option for exporting values as CSV is very useful looking at lots of records at the same time, but ideally I would like to be able to edit and add to the CSV file and then use it to update the source thesaurus.

I have had a look at the documentation and can not find an option for this. The only note I have found is that if you try to upload terms in the tabulated form it ignores all terms that already have URIs.

So, my question is is it possible, perhaps using the APIs to export data from OpenTheso2 in some form of readable text, edit and add to this and then update a thesaurus with the new information? New information could include new terms or edits to existing terms.

Thanks

**Comment by miledrousset** [comment]
Hello,
You can try this solution: 
- use the module (Thesaurus workshop) 
- you have a number of actions available to apply to the current thesaurus 

Let me know if you don't succeed.

Miled
<img width="953" alt="Capture d’écran 2024-01-29 à 15 49 05" src="https://github.com/miledrousset/Opentheso2/assets/3404662/2ccfb19e-e457-46e7-bd29-e497dc25ddfc">
<img width="1241" alt="Capture d’écran 2024-01-29 à 15 49 47" src="https://github.com/miledrousset/Opentheso2/assets/3404662/0fe254fd-86e9-4de9-a3d0-ea34fa95f477">

**Comment by jpadfield** [comment]
Thanks, that looks great, sorry I missed it, I will have a go.
