### ISSUE TITLE
Problème d'import

### ISSUE THREAD

**Issue by SarahMucem** [MOM-CNRS/Opentheso#90]
Bonjour,

j'essaie d'importer un fichier csv mais la moitié environ des concepts ne s'importent pas, alors que j'ai l'impression qu'ils sont structurés de la même manière que ceux qui ne posent pas de problème. Je n'arrive pas à voir ce qui différencie les concepts importés correctement de ceux qui bugguent. Ce n'est a priori pas une question d'espace, ni de caractère accentué, l'encodage est bien en UTF 8.

Ci joint le fichier que j'essaie d'importer et la copie du message d'erreur.
[Erreur concept.docx](https://github.com/miledrousset/Opentheso2/files/14649346/Erreur.concept.docx)
[categorie_doc_2.csv](https://github.com/miledrousset/Opentheso2/files/14649347/categorie_doc_2.csv)

Ici ce qui a été importé. https://[opentheso.huma-num.fr/opentheso/?idt=th774](https://opentheso.huma-num.fr/opentheso/?idt=th774)

Merci pour votre aide

Sarah

**Comment by miledrousset** [comment]
Bonjour,
J'ai regardé votre fichier, il y a un problème à corriger au niveau de la colonne (URI) : la méthode d'import détecte automatiquement les identifiants en éliminant les données avant un (/). Dans votre exemple, vous avez (2DOC222/4) ça se traduit en (4), puis un autre exemple avec (2DOC150/4) ça produit le même identifiant (4).
Il n'est pas recommander de donner des identifiants avec des (/).

Il y a 2 solutions pour vous : 

1. remplacer les (/) dans l'URI par des (_) ou autre séparateur
2. Si vous voulez malgré tout garder les (/),  il faut ajouter une colonne au tableau avec le titre (identifier) et copier toutes les infos de la colonne URI dedans (Il ne faut pas supprimer la colonne (URI).

Tenez moi au courant.
Miled

**Comment by SarahMucem** [comment]
Merci beaucoup, ça a marché parfaitement
