### ISSUE TITLE
Can lists of terms be removed from a group/collection in one go

### ISSUE THREAD

**Issue by jpadfield** [MOM-CNRS/Opentheso#96]
Hi,

I have looked at the tool box and can see how a list of terms can be added and how other terms can be edited, but I have not managed to work out the required syntax or labels to edit the "skos:member" value for terms. I have tried using "new_skos:member" but it does not seem to be recognised, or my syntax for the current value is incorrect.

Could you confirm if I should be able to todo this and if you provide and example.

Thanks

Joe

**Comment by miledrousset** [comment]
Hello,
You can remove a list of concepts (by branch) from a collection in one go. To do this, you need to choose the action described in the screenshot.
If that's not what you're asking for, please give me more details.
<img width="1690" alt="Capture d’écran 2024-04-08 à 14 00 01" src="https://github.com/miledrousset/Opentheso2/assets/3404662/d603c527-5a96-46aa-b215-e71ce314495a">

**Comment by jpadfield** [comment]
Yes, I found that one thanks :-)

My particular use case is that I have entered a larger number of terms which are part of an external vocabulary, within that data set they use an number of linking or grouping terms. These grouping terms are needed to ensure a correct hierarchical structure but they would not be used in a dropdown list of terms that people would use as keywords. As the overall list is large I used the add list of concepts by branch to add them all to a collection, but I now wanted to remove all of the terms which start with "<" and end with ">".

It seem my option is to remove them all as you have indicated and then use external scripting to generate a csv file indicating which ones should be added back in. But I was just curious to see if there was a batch remove from collection option at all. 

Thanks

**Comment by miledrousset** [comment]
You always have the option of exporting the thesaurus as a CSV file, then making any necessary corrections. Then import the thesaurus in CSV format

**Comment by jpadfield** [comment]
I have explored several of the importing options for CSV (Toolbox / Thesaurus workshop), but I have not come across an export to CSV option (apart from the alignment one), or does this need to be a server side action? 

If there are exporting options in the GUI can these be used for back up and recovery? So returning a thesaurus to a previous stable state if something goes wrong, or again is this a server side action?

Thanks

**Comment by miledrousset** [comment]
To export or import a thesaurus, there's a specific module for that. see the screenshots.
<img width="276" alt="Capture d’écran 2024-04-08 à 15 44 10" src="https://github.com/miledrousset/Opentheso2/assets/3404662/3d0bec8d-3917-4c1e-82b1-358d27667ebc">
<img width="1556" alt="Capture d’écran 2024-04-08 à 15 44 27" src="https://github.com/miledrousset/Opentheso2/assets/3404662/a347d536-1d63-493c-b840-e4011675b41e">
<img width="1752" alt="Capture d’écran 2024-04-08 à 15 44 40" src="https://github.com/miledrousset/Opentheso2/assets/3404662/f3a14ed9-51ec-437a-9632-b92400984234">

**Comment by jpadfield** [comment]
Thank you very much for this, I think I have more than enough to go forward :-)
Thanks again
Joe

**Comment by jpadfield** [comment]
Sorry, one more question, just to check, if one exports a Thesaurus to CSV, edits it, then imports it again, this process seems to create a new thesaurus. Is there a way of ensuring that it just updates the existing one? I used the existing thesaurus id in the name field, but this was obviously not correct ...

**Comment by miledrousset** [comment]
The import will create a new thesaurus, not an update. It's very difficult to propose a replacement for an existing thesaurus, as semantic relationships complicate matters. Perhaps at a later date, we will offer this functionality.
